# Uncomment the next line to define a global platform for your project
platform :ios, '13.1'

target 'Wins Pool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wins Pool
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Google'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'FirebaseFirestoreSwift', '~> 7.0-beta'
end
